language: node_js
node_js:
  - "0.10"

notifications:
  slack: ucsdtt:swWUoEV6gZT7X2j1mThcrLz8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox