FORMAT: 1A

# Garnett API
Garnett API is an internal service for UCSD Theta Tau's *Garnett* web application. Garnett has a
timeline-focused approach that encourages social networking based on events.

###Useful Links
+ [Github](https://github.com/UCSDTT/Garnett/)
+ [Understanding HTTP](http://code.tutsplus.com/tutorials/http-the-protocol-every-web-developer-must-know-part-1--net-31177)

###Errors and Suggestions
Please notify the Garnett API developers on Slack if there are any inconsistencies with 
the API or if you have any feature requests.

# Group Members
Members related resources of the **Garnett API**

## Members Collection [/notes]
Actions for manipulating the collection of members
### List all Members [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "firstname": "Michael",
            "lastname": "Luo",
            "username": "mzluo",
            "password": "password",
            "email": "mzluo@tt.com",
            "phonenumber": "5109995555",
            "startyear": 2011,
            "gradyear": 2015,
            "major": "Computer Science",
            "class": "Iota",
            "securityquestion": "This is a security question",
            "securityanswer": "This is a security question answer",
            "activeid": 110,
            "createdon": "2014-12-01T22:32:40.898Z"
        },
        {
            "id": 2,
            "firstname": "Benjie",
            "lastname": "Genchel",
            "username": "bgenchel",
            "password": "banana",
            "email": "bgenchel@tt.com",
            "phonenumber": "3459590",
            "startyear": 2010,
            "gradyear": 2014,
            "major": "Electrical Engineering",
            "class": "Eta",
            "securityquestion": "This is a security question",
            "securityanswer": "This is a security answer",
            "activeid":111,
            "createdon": "2014-12-01T22:32:40.898Z"
        }]

### Create a Member [POST]
+ Request (application/json)

        {
            "firstname": "Michael",
            "lastname": "Luo",
            "username": "mzluo",
            "password": "password",
            "email": "mzluo@tt.com",
            "phonenumber": "5109995555",
            "startyear": 2011,
            "gradyear": 2015,
            "major": "Computer Science",
            "class": "Iota",
            "securityquestion": "This is a security question",
            "securityanswer": "This is a security question answer",
            "activeid": 110,
        }

+ Response 201 (application/json)

        {
            "id": 1,
            "firstname": "Michael",
            "lastname": "Luo",
            "username": "mzluo",
            "password": "password",
            "email": "mzluo@tt.com",
            "phonenumber": "5109995555",
            "startyear": 2011,
            "gradyear": 2015,
            "major": "Computer Science",
            "class": "Iota",
            "securityquestion": "This is a security question",
            "securityanswer": "This is a security question answer",
            "activeid": 110,
            "createdon": "2014-12-01T22:32:40.898Z"
        }

## Member [/members/{memberid}]
Manipulate a single member object

+ Parameters
    + memberid (required, number, `1`) ... Numeric `id` of the Member to perform action with. Has example value.

### Retrieve a Member [GET]
+ Response 200 (application/json)

    + Body

            [{
                "id": 1,
                "firstname": "Michael",
                "lastname": "Luo",
                "username": "mzluo",
                "password": "password",
                "email": "mzluo@tt.com",
                "phonenumber": "5109995555",
                "startyear": 2011,
                "gradyear": 2015,
                "major": "Computer Science",
                "class": "Iota",
                "securityquestion": "This is a security question",
                "securityanswer": "This is a security question answer",
                "activeid": 110,
                "createdon": "2014-12-01T22:32:40.898Z"
            }]

### Remove a Member [DELETE]
+ Response 204
